/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as ConsultCompleteRouteImport } from './routes/consult.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultCompleteRoute = ConsultCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ConsultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consult': typeof ConsultRouteWithChildren
  '/consult/complete': typeof ConsultCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consult': typeof ConsultRouteWithChildren
  '/consult/complete': typeof ConsultCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consult': typeof ConsultRouteWithChildren
  '/consult/complete': typeof ConsultCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/consult' | '/consult/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/consult' | '/consult/complete'
  id: '__root__' | '/' | '/auth' | '/consult' | '/consult/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConsultRoute: typeof ConsultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult/complete': {
      id: '/consult/complete'
      path: '/complete'
      fullPath: '/consult/complete'
      preLoaderRoute: typeof ConsultCompleteRouteImport
      parentRoute: typeof ConsultRoute
    }
  }
}

interface ConsultRouteChildren {
  ConsultCompleteRoute: typeof ConsultCompleteRoute
}

const ConsultRouteChildren: ConsultRouteChildren = {
  ConsultCompleteRoute: ConsultCompleteRoute,
}

const ConsultRouteWithChildren =
  ConsultRoute._addFileChildren(ConsultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConsultRoute: ConsultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
